from app.schemas.candidate import Candidate, CandidateCreate
from app.schemas.auth import UserRole
from app.schemas.image import SetImage
from app.schemas.import_job import (
    ImportJob,
    ImportJobPage,
    ImportJobPatch,
    ImportRequest,
    JobStatus,
    JobType,
)
from app.schemas.merge import (
    MergeCandidate,
    MergeCandidatePage,
    MergeCandidateStatus,
    MergeComponentScores,
    MergeDecision,
    MergeDecisionAction,
    MergeScore,
    SetProviderSource,
)
from app.schemas.profile import SearchProfile, SearchProfileCreate, SearchProfileUpdate
from app.schemas.rights import (
    RightsDecisionAction,
    RightsDecisionEvent,
    RightsEvidence,
    RightsEvidenceInput,
    RightsEvidenceType,
    RightsReview,
    RightsReviewApproval,
    RightsReviewCreate,
    RightsReviewPage,
    RightsReviewResolution,
    RightsReviewStatus,
)
from app.schemas.set import (
    ReviewStatus,
    SetDetail,
    SetPage,
    SetPatch,
    SetSource,
    SetSummary,
)

__all__ = [
    "Candidate",
    "CandidateCreate",
    "ImportJob",
    "ImportJobPage",
    "ImportJobPatch",
    "ImportRequest",
    "JobStatus",
    "JobType",
    "MergeCandidate",
    "MergeCandidatePage",
    "MergeCandidateStatus",
    "MergeComponentScores",
    "MergeDecision",
    "MergeDecisionAction",
    "MergeScore",
    "ReviewStatus",
    "RightsDecisionAction",
    "RightsDecisionEvent",
    "RightsEvidence",
    "RightsEvidenceInput",
    "RightsEvidenceType",
    "RightsReview",
    "RightsReviewApproval",
    "RightsReviewCreate",
    "RightsReviewPage",
    "RightsReviewResolution",
    "RightsReviewStatus",
    "SearchProfile",
    "SearchProfileCreate",
    "SearchProfileUpdate",
    "SetDetail",
    "SetImage",
    "SetPage",
    "SetPatch",
    "SetProviderSource",
    "SetSource",
    "SetSummary",
    "UserRole",
]
