#!/usr/bin/env bash
set -Eeuo pipefail

umask 077

ENV_FILE="${1:-.env.production}"
PROJECT_REF="smoevguhtsclfcmjwwhq"
SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
SUPABASE_PUBLISHABLE_KEY="sb_publishable_hZXd8eJ4dGRwfHSW8u0Xog_JFhFD7s0"
POOLER_HOST="aws-0-eu-west-1.pooler.supabase.com"
POOLER_USER="postgres.${PROJECT_REF}"
API_DOMAIN="api.syco23.org"
FRONTEND_ORIGIN="https://syco23-setcrawler.vercel.app"
ACME_EMAIL="emilach82@gmail.com"

command -v python3 >/dev/null 2>&1 || {
  echo "ERROR: python3 is required to encode the database password safely." >&2
  exit 1
}

if [[ -e "$ENV_FILE" ]]; then
  read -r -p "$ENV_FILE already exists. Replace it? [y/N] " answer
  case "$answer" in
    y|Y|yes|YES)
      backup="${ENV_FILE}.backup.$(date -u +%Y%m%dT%H%M%SZ)"
      cp --preserve=mode "$ENV_FILE" "$backup"
      echo "Existing file backed up to $backup"
      ;;
    *)
      echo "No changes made."
      exit 0
      ;;
  esac
fi

read -r -s -p "Supabase database password: " DB_PASSWORD
printf '\n'

if [[ -z "$DB_PASSWORD" ]]; then
  echo "ERROR: database password must not be empty." >&2
  exit 1
fi

ENCODED_DB_PASSWORD="$({ DB_PASSWORD="$DB_PASSWORD" python3 - <<'PY'
import os
from urllib.parse import quote

print(quote(os.environ["DB_PASSWORD"], safe=""))
PY
})"
unset DB_PASSWORD

read -r -p "Optional YouTube API key (leave empty for fixture mode): " YOUTUBE_API_KEY

PROVIDER_MODE="fixture"
if [[ -n "$YOUTUBE_API_KEY" ]]; then
  read -r -p "Enable live provider mode now? [y/N] " enable_live
  case "$enable_live" in
    y|Y|yes|YES) PROVIDER_MODE="live" ;;
  esac
fi

TMP_FILE="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
trap 'rm -f "$TMP_FILE"' EXIT

cat >"$TMP_FILE" <<EOF
# Generated by scripts/configure-production-env.sh
# Secrets remain on this host. Never commit this file.

API_DOMAIN=${API_DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
CORS_ORIGINS=${FRONTEND_ORIGIN}

SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_PUBLISHABLE_KEY}
SUPABASE_JWT_AUDIENCE=authenticated
DATABASE_URL=postgresql://${POOLER_USER}:${ENCODED_DB_PASSWORD}@${POOLER_HOST}:5432/postgres?sslmode=require&gssencmode=disable

PROVIDER_MODE=${PROVIDER_MODE}
YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
SCRAPER_USER_AGENT=syco23-setcrawler/0.2(+contact:${ACME_EMAIL})
SCRAPER_REQUEST_DELAY_MS=5000
FTM_SCRAPER_ENABLED=false
FTM_MAX_PAGES_PER_RUN=25
PROVIDER_REQUEST_TIMEOUT_SECONDS=20
PROVIDER_OUTPUT_LIMIT_BYTES=1048576
YT_DLP_BIN=yt-dlp

JOB_CLAIM_TTL_SECONDS=300
JOB_REDRIVE_INTERVAL_SECONDS=60
JOB_REDRIVE_BATCH_SIZE=100
EOF

chmod 600 "$TMP_FILE"
mv "$TMP_FILE" "$ENV_FILE"
trap - EXIT

# Validate interpolation without printing resolved secret values.
docker compose \
  --env-file "$ENV_FILE" \
  -f docker-compose.production.yml \
  config --quiet

echo "Configured $ENV_FILE with mode 600."
echo "Provider mode: $PROVIDER_MODE"
echo "Next: ./scripts/deploy-production.sh $API_DOMAIN"
